title: Sinai Olivares
tagline: Portfolio
theme: jekyll-theme-cayman
description: >-
  Hi! My name is Sinai and I'm a physics teacher turned data analyst. I'm currently working on helping local businesses develop better data practices so they can obtain insights and take better decisions based on data.
