theme: jekyll-theme-cayman
title: Sinai Olivares
tagline: Portfolio
description: >-
  Hi! My name is Sinai and I`m a physics teacher turned data analyst
  
social-network-links:
  email: "someone@example.com"
  twitter: msof
  linkedin: msof
